[package]
name = "rocket_project"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features=["json"]}
serde = {version = "1.0.214", features=["derive"]}
serde_json = "1.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }